accounts/urls.py
from django.urls import path
from django.contrib.auth.views import  LogoutView

from accounts.views import MyLoginView, SignUpView

urlpatterns = [
    path("signup/", SignUpView.as_view(), name="signup"),
    path("login/", MyLoginView.as_view(), name="login"),
    path("logout/", LogoutView.as_view(), name="logout"),
    
]

compe/urls.py
from django.urls import path

from .views import CategoryListView, ProblemListView,ChoiceDetailView, results_view


app_name = 'compe'
urlpatterns = [
    path('', CategoryListView.as_view(), name='category'),
    path('problem/<int:pk>/', ProblemListView.as_view(), name='problem'),
    path('choice/<int:pk>/', ChoiceDetailView.as_view(), name='choice_detail'),
    path('results/', results_view, name='results'),
]

config/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static


urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('compe.urls')),
    path('accounts/', include('accounts.urls')),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

accounts/models.py
from django.db import models

# Create your models here.

compe/models.py
from django.db import models


class Category(models.Model):
    title = models.CharField(max_length=200)
    image = models.ImageField(upload_to='uploads/', null=True, blank=True)
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)
    is_published = models.BooleanField(default=False)

    def __str__(self):
        return self.title


class Problem(models.Model):
    title = models.CharField(max_length=200)
    created_at = models.DateTimeField(auto_now=True)
    updated_at = models.DateTimeField(auto_now_add=True)
    is_published = models.BooleanField(default=False)

    category = models.ForeignKey(Category, on_delete=models.CASCADE, related_name='Categorys')

    def __str__(self):
        return self.title


class Choice(models.Model):
    title = models.CharField(max_length=100)
    completed = models.IntegerField(default=120)
    unfinished = models.IntegerField(default=0)
    zone = models.IntegerField(default=60)
    total = models.IntegerField(default=0)

    problem = models.ForeignKey(Problem, on_delete=models.CASCADE, related_name='Problems')

    def __str__(self):
        return self.title

compe/forms.py
from django import forms


class ChoiceForm(forms.ModelForm):
    selected = forms.ChoiceField(choices=[('完登', 'completed'), ('未完登', 'unfinished'), ('ゾーン', 'zone')])

accounts/views.py
from django.views.generic import CreateView
from django.contrib.auth.views import LoginView
from django.contrib.auth.forms import UserCreationForm
from django.urls import reverse_lazy

class MyLoginView(LoginView):
    template_name = "accounts/login.html"
    redirect_authenticated_user = True


class SignUpView(CreateView):
    template_name = 'accounts/signup.html'
    form_class = UserCreationForm
    success_url = reverse_lazy("compe:category")

compe/views.py
from typing import Any
from django.db.models.query import QuerySet
from django.shortcuts import render, get_object_or_404, redirect
from django.views.generic import ListView, DetailView, TemplateView
from django.contrib.auth.mixins import LoginRequiredMixin
from django.contrib.auth.decorators import login_required


from compe.models import Category, Problem, Choice, Choice
from compe.forms import ChoiceForm


class CategoryListView(ListView):
    model = Category
    template_name = 'compe/category_list.html'
    context_object_name = 'categories'


class ProblemListView(ListView):
    model = Problem
    template_name = 'compe/problem_list.html'
    context_object_name = 'problems'


    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        category_id = self.kwargs['pk']
        category = get_object_or_404(Category, id=category_id)
        problems = category.Categorys.all()
        context['category'] = category
        context['problems'] = problems
        return context


class ChoiceDetailView(DetailView):
    model = Choice
    template_name = 'compe/choice_detail.html'
    context_object_name = 'choice'
    form_class = ChoiceForm

    def get_queryset(self):
        query = super().get_queryset()
        return query

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        problem_id = self.kwargs['pk']
        problem = get_object_or_404(Problem, id=problem_id)
        choices = problem.Problems.all()
        context['problem'] = problem
        context['choices'] = choices
        return context


@login_required
def choice(request, problem_id):
    if request.method == 'POST':
        form = ChoiceForm(request.POST)
        if form.is_valid():
            selected = form.cleaned_data['selected']
            choice = Choice.objects.first()
            if selected == 'completed':
                choice.completed += 1
            elif selected == 'unfinished':
                choice.unfinished += 1
            elif selected == 'zone':
                choice.zone += 1
            choice.total = choice.completed + choice.unfinished + choice.zone
            choice.save()
            print(form.cleaned_data)
            return redirect('results')
    else:
        form = ChoiceForm()
    return render(request, 'choice.html', {'form': form})

@login_required
def results_view(request):
    choice = Choice.objects.first()
    return render(request, 'results.html', {'choice': choice})

accounts/templates/accounts/login.html
{% extends 'base.html' %}


{% block content %}
<div class="mt-4">
    <form action="" method="POST">
        {% csrf_token %}
        <table class="table">
            {{form.as_table}}
        </table>
        <div class="d-grid gap-2 col-6 mx-left">
            <input class="btn btn-success" type="submit" value="送信">
        </div>
    </form>
</div>
{% endblock content %}
    

accounts/templates/accounts/signup.html
{% extends 'base.html' %}


{% block content %}
<div class="mt-4">
    <h2>会員登録</h2>
    <form action="" method="POST">
        {% csrf_token %}
        <table class="table">
            {{form.as_table}}
        </table>
        <div class="d-grid gap-2 col-6 mx-left">
            <input class="btn btn-success" type="submit" value="送信">
        </div>
    </form>
</div>
{% endblock content %}

compe/templates/compe/category_list.html
{% extends 'base.html' %}
{% load django_bootstrap5 %}
{% load static %}



{% block content %}
<div class="row">
    <div class="col-9">
        <h2>カテゴリー一覧</h2>
        {% for category in object_list %}
        <div class="card bg-dark text-white">
            <img src="{{category.image.url}}" class="card-img" width='30%' height="200" alt="{{category.title}}">
            <div class="card-img-overlay">
                <h5 class="card-title">{{category.title}}</h5>
                <p class="card-text">This is a wider card with supporting text below as a natural lead-in to additional content. This content is a little bit longer.</p>
                {% if user.is_authenticated %}
                <a href="{% url 'compe:problem' category.pk %}" class="btn btn-primary">開く</a>
                {% endif %}
            </div>
        </div>
        {% endfor %}
    </div>
    <div class="col-3">
        <div class="p-4">
            <h4>課題一覧</h4>
            <ul class="list-group list-group-flush">
                <li class="list-group-item">{{ problem }}</li>
                <li class="list-group-item">{{ problem }}</li>
                <li class="list-group-item">{{ problem }}</li>
                <li class="list-group-item">{{ problem }}</li>
            </ul>
        </div>
        <div class="p-4">
            <span class="badge bg-light text-dark m-1">Light</span>
            <span class="badge bg-light text-dark m-1">Light</span>
            <span class="badge bg-light text-dark m-1">Light</span>
        </div>
    </div>
</div>

{% endblock content %}

compe/templates/compe/choice_detail.html
{% extends 'base.html' %}
{% load django_bootstrap5 %}
{% load static %}

{% block content %}

<h3>{{ choice.title }}の課題</h3>
<div class="card">
    <h5 class="card-header">{{problem.title}}の課題</h5>
    <div class="card-body m-1">
        <form method="post">
            {% csrf_token %}
            {{ form.as_p }}
            <input type="submit" value="投票">
        </form>
    </div>
</div>

{% endblock content %}

compe/templates/compe/problem_list.html
{% extends 'base.html' %}
{% load django_bootstrap5 %}
{% load static %}


{% block content %}

{% for problem in problems %}
<div class="card" style="width: 18rem;">
    <div class="card-body m-1">
        <h5 class="card-title">{{category.title}}</h5>
        <h6 class="card-subtitle mb-2 text-muted">{{ problem.title }}</h6>
        <p class="card-text">Some quick example text to build on the card title and make up the bulk of the card's content.</p>
        {% if user.is_authenticated %}
        <a href="{% url 'compe:choice_detail' problem.pk %}" class="card-link">開く</a>
        <a href="{% url 'compe:category' %}" class="card-link">トップ</a>
        {% endif %}
    </div>
</div>
{% endfor %}

{% endblock content %}

compe/templates/compe/results.html
{% extends 'base.html' %}
{% load django_bootstrap5 %}
{% load static %}

{% block content %}
<div class="card text-center">
    <div class="card-header">
        現在のあなたの得点
    </div>
    <div class="card-body">
        <h1>選択結果</h1>
            <p>Total: {{ choice.total }}</p>
        <input type="button" value="戻る" onClick="javascript:history.go(-1)">
    </div>
    <div class="card-footer text-muted">
        today
    </div>
</div>
<h1></h1>

<p></p>


{% endblock content %}

templates/base.html
{% load django_bootstrap5 %}
{% load static %}
<!doctype html>
<html lang="ja">
    <head>
        <meta charset="utf-8">
        <meta name="viewport" content="width=device-width, initial-scale=1">
        <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-EVSTQN3/azprG1Anm3QDgpJLIm9Nao0Yz1ztcQTwFspd3yD65VohhpuuCOmLASjC" crossorigin="anonymous">
        <title>competition</title>
    </head>
    <body>
        <nav class="navbar navbar-expand-lg bavbar-dark bg-dark">
            <div class="container">
                <a class="navbar-brand" href="{% url 'compe:category' %}">コンペティション</a>
                <div class="d-flex me-4 barbar-dark bg-dark">
                    <ul class="navbar-nav">
                        {% if user.is_authenticated %}
                        <li class="nav-item">
                            <a class="nav-link text-white disabled" href="">{{ user.username }}</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link" href="{% url 'logout' %}">ログアウト</a>
                        </li>
                        {% else %}
                        <li class="nav-item">
                            <a class="nav-link" href="{% url 'login' %}">ログイン</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link" href="{% url 'signup' %}">会員登録</a>
                        </li>
                        {% endif %}
                        <li class="nav-item">
                        </li>
                    </ul>
                </div>
            </div>

        </nav>
        {% if category.image %}
            <img src="{{category.image.url}}" alt="category.title" width="100%" height="450">
        {% endif %}
        <div class="container">
            {% block content %}

            {% endblock content %}
        </div>


        <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/js/bootstrap.bundle.min.js" integrity="sha384-MrcW6ZMFYlzcLA8Nl+NtUVF0sA7MsXsP1UyJoMp4YLEuNSfAP+JcXn/tWtIaxVXM" crossorigin="anonymous"></script>

    </body>
</html>